spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          timeout: 5
          clone-on-start: true
          force-pull: true
          uri: https://github.com/dkotrada/config-repo
          default-label: main

server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
